import { GoogleGenAI } from "@google/genai";

const blogTopics = [
  {
    category: "billboard",
    topic:
      "How Billboard Advertising Helps Local Businesses Build Brand Awareness",
  },
  {
    category: "digital-ooh",
    topic: "How Digital Billboards Are Changing Outdoor Advertising in India",
  },
  {
    category: "transit-advertising",
    topic: "Why Transit Advertising Is Effective for Reaching Daily Commuters",
  },
  {
    category: "airport-advertising",
    topic: "Why Airport Advertising Is Valuable for Premium Brands",
  },
  {
    category: "metro-advertising",
    topic: "How Metro Advertising Helps Brands Reach Urban Audiences",
  },
  {
    category: "outdoor-advertising",
    topic: "Why Outdoor Advertising Still Matters in the Digital Marketing Era",
  },
  {
    category: "ooh-trends",
    topic: "Outdoor Advertising Trends to Watch in 2026",
  },
  {
    category: "advertising-strategy",
    topic: "How to Build an Effective OOH Advertising Campaign",
  },
  {
    category: "location-guide",
    topic: "How to Choose the Right Billboard Location for Your Campaign",
  },
];



const ai = new GoogleGenAI({
    apiKey: process.env.GEMINI_API_KEY
});

export async function GenerateBlog() {

  const selectedTopic = blogTopics[Math.floor(Math.random() * blogTopics.length)];

  const topic = selectedTopic.topic
  const category = selectedTopic.category


 try {
   const response = await ai.models.generateContent({
    model: "gemini-3.6-flash",

    contents: `
You are an expert content writer specializing in:

- Outdoor Advertising
- OOH Advertising
- Billboard Advertising
- Digital OOH
- Transit Advertising
- Airport Advertising
- Metro Advertising
- Mall Advertising
- Mobile Advertising
- Advertising trends

Write a professional SEO-friendly blog for a company website
that provides outdoor advertising services.

Topic:
${topic}

Blog Category:
${category}

The topic and category have already been decided by the application.

Do NOT change the topic.

Do NOT change, rename, reinterpret, or generate another
blog category.

The category provided above must be used as the category
for this article.

Requirements:

1. Create a strong and professional title.
2. Create a short URL slug.
3. Generate relevant SEO keywords.
4. Generate a short summary.
5. Generate a detailed blog article.
6. The article should be approximately 1000-1500 words.
7. Use HTML only inside the content field.
8. Use <h3> for section headings.
9. Use <p> for paragraphs.
10. You may use <ul>, <ol> and <li> when useful.
11. Do NOT use Markdown.
12. Do NOT include <html>, <body>, <head>, <h1> or CSS.
13. Do not mention that the article was generated by AI.
14. Keep the writing professional and useful for businesses.
15. Naturally include relevant keywords without keyword stuffing.
16. Include an introduction and conclusion.
17. Do not invent fake statistics, research studies, companies,
    URLs or citations.
18. If a statistic cannot be verified, avoid giving an exact number.
19. Make the content relevant to the Indian advertising market
    where appropriate.
20. Do not use [1], [2], [3] or similar fake citation references.

Return ONLY valid JSON.

Return exactly this structure:

{
  "title": "",
  "url": "",
  "keywords": "",
  "summary": "",
  "content": ""
}

Important:

- Do NOT return blogCategory.
- The application will add the blogCategory automatically.
- summary must contain HTML and normally be one <p>...</p>.
- content must contain valid HTML.
- keywords must be a comma-separated string.
- url must be lowercase and URL-friendly.
`,

    config: {
      responseMimeType: "application/json",
    },
  });

  const text = response.text;

  

  const blog = JSON.parse(text);

  return {
    ...blog,
    blogCategory: category,
  };
  
 } catch (error) {
  console.log("error occured",error)
 }
}

const {title,url,keywords,summary,content,blogCategory} = await GenerateBlog();
console.log(blog)

// const query = `
//   INSERT INTO blogs
//   (
//     title,
//     url,
//     image,
//     blogCategory,
//     keywords,
//     summary,
//     created_by,
//     CreatedOn,
//     UpdatedOn,
//     content,
//     popularity
//   )
//   VALUES (?, ?, NULL, ?, ?, ?, ?, NOW(), NOW(), ?, ?)
// `;

// const data = await executeQuery(
//   query,
//   [
//     blog.title,
//     blog.url,
//     blog.blogCategory,
//     blog.keywords,
//     blog.summary,
//     "abhishek",
//     blog.content,
//     0,
//   ],
//   "CRM",
//   next
// );



